spring:
  application:
    name: toshi

  profiles:
    active: local   # default profile

server:
  port: 8083

logging:
  level:
    org.springframework.r2dbc: INFO

razorpay:
  key: ${RAZORPAY_KEY:}
  secret: ${RAZORPAY_SECRET:}



