spring:
  r2dbc:
   # url: r2dbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}

    url: r2dbc:postgresql://postgres:MEXxHiAhLNdtZhVfXZFppotvDhWJpUGy@postgres.railway.internal:5432/railway
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    initialization-mode: never

sql:
  init:
    mode: never

server:
  port: ${PORT:8083}

razorpay:
  key: ${RAZORPAY_KEY}
  secret: ${RAZORPAY_SECRET}
